image: cm0x4d/ubuntu-qt5-cmake

stages:
  - build
  - test

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build/src/gui/ttga
      - build/src/test/ttga-test

test:
  stage: test
  script:
    - build/src/test/ttga-test

